//
// Created by kirill on 13.04.2020.
//

#ifndef SIGNATURE_ERROR_CODES_H
#define SIGNATURE_ERROR_CODES_H

enum ErrorCodes
{
    SUCCESS = 0,
    BAD_UNIT_SIZE,
    DID_NOT_RECEIVE_UNIT_SIZE,
    NOT_ENOUGH_ARGUMENTS,
    FILE_IN_NOT_EXISTS,
    FILE_OUT_NOT_EXISTS,
};

#endif //SIGNATURE_ERROR_CODES_H